# Generated by Django 2.2.5 on 2022-01-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220104_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.ManyToManyField(to='blog.Category', verbose_name='دسته\u200cبندی'),
        ),
    ]
