# Generated by Django 2.2.5 on 2022-01-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Category',
            new_name='category',
        ),
    ]
